server:
  port: 8761
spring:
  application:
    name: eureka-server
#eureka
eureka:
  client:
    # 是否将自身注册到注册中中心
    register-with-eureka: false
    # 是否从Eureka获取注册信息
    fetch-registry: false
    # 设置与Eureka Server交互地址，多个地址使用英文逗号分隔
    service-url:
      defaultZone: http://${spring.application.name}:${server.port}/eureka/
