server:
  port: 8090  #服务端口号
spring:
  application:
    name: redis #服务名称--调用的时候根据名称来调用该服务的方法
  #redis
  redis:
    database: 0
    url: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 5000
eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:8761/eureka/
